meta_product_name: "Jessie Baxter"
meta_title: "Jessie Baxter | Founder, Product Manager & Software Developer"
meta_description: "Check out what I've built and say hi!"
meta_image: "cover.png"
twitter_account: "@jessiebbaxter"